wandb_version: 1

config:
  desc: null
  value: config.yaml
save_root:
  desc: null
  value: checkpoints
exp_name:
  desc: null
  value: mp-2024
seed:
  desc: null
  value: 123
log_level:
  desc: null
  value: 20
data_root:
  desc: null
  value: data/private
num_rays_per_img:
  desc: null
  value: 512
bg_color:
  desc: null
  value: white
lr:
  desc: null
  value: 0.001
beta1:
  desc: null
  value: 0.5
beta2:
  desc: null
  value: 0.999
weight_decay:
  desc: null
  value: 0
epochs:
  desc: null
  value: 8000
batch_size:
  desc: null
  value: 2
workers:
  desc: null
  value: 8
save_every:
  desc: null
  value: 1500
log_every:
  desc: null
  value: 100
num_pts_per_ray:
  desc: null
  value: 256
near:
  desc: null
  value: 1.0
far:
  desc: null
  value: 3.0
out_dim:
  desc: null
  value: 4
num_layers:
  desc: null
  value: 4
hidden_dim:
  desc: null
  value: 256
activation:
  desc: null
  value: relu
skip:
  desc: null
  value: 2
num_freq:
  desc: null
  value: 5
max_freq:
  desc: null
  value: 5
valid_every:
  desc: null
  value: 500
mip:
  desc: null
  value: 2
sigma_thres:
  desc: null
  value: 50.0
chunk_size:
  desc: null
  value: 10240
num_pts_per_ray_render:
  desc: null
  value: 128
save_img:
  desc: null
  value: false
wandb_id:
  desc: null
  value: null
wandb:
  desc: null
  value: true
wandb_name:
  desc: null
  value: mp_test
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717776378
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 2
      - 13
      - 14
      - 16
      - 23
      - 61
      4: 3.10.12
      5: 0.17.1
      8:
      - 6
      13: linux-x86_64
